# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18bd7b02b48e0dc5a50a24f5df1a667a1c2ed53bf8447b99486f998b3dbec9f782a1e68a4ce0d312753c81d1f7b68fd0743bdbc51d58759b64afc5d9835f0bb7

test:
  secret_key_base: 5ef6b0eae83d66e02abb296c04eec30c60ae3e6028a6a082f5c9f0225982122cdb0ad2a2b8f37ac989803ae9aee2ff37af83b1591eba3e64af8b029e8f86fe21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
